name: Docker Image CI

on:
  schedule:
    - cron: "0 10 * * 1"
  push:
    branches:
      - 'master'
      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: getdate
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pilbbq/deluge:latest, pilbbq/deluge:autobuilt, pilbbq/deluge:${{ steps.getdate.outputs.time }}
